Feature/create database migration
RodolfoMRibeiro/backend_test_dimi pull request #4
Opened 2022-07-23 17:29 UTC by RodolfoMRibeiro

Here I fixed gorm tags and migrated successfully all the tables to the database that must be created before running the application. At the same time, it was created a way to collect environment variables from .env file and set a specialized struct with these data.

2022-07-23 19:02 UTC, R-o-d-r-i-g-o requested changes
dá uma olhada aí se todos os comentários estão em acordo com a realidade

2022-07-23 19:02 UTC, R-o-d-r-i-g-o commented on db/database.go
> +	databaseStringConfig := fmt.Sprintf("%s:%s@tcp(%s:%s)/%s", envVars.User, envVars.Password, envVars.Host, envVars.Port, envVars.Database)
Olá @RodolfoMRibeiro, boa tarde!

Nesta parte também colocaria especificações no link sobre o formato UTF-8 etc. 
Por exemplo: "?charset=utf8mb4&parseTime=True&loc=Local"

2022-07-23 19:02 UTC, R-o-d-r-i-g-o commented on db/database.go
> +	if err != nil {
fiz uma função própria para reciclar estruturas como essa no diretório util, dá uma olhada lá.

2022-07-23 19:02 UTC, R-o-d-r-i-g-o commented on db/entity/environmentVariables.go
> +func (env *EnvironmentVariables) Load() {
load é no sentido de carregar se não me engano. Neste caso, colocaria feed<nome da struct> no nome da função

2022-07-23 20:01 UTC, RodolfoMRibeiro commented on db/database.go
> +	databaseStringConfig := fmt.Sprintf("%s:%s@tcp(%s:%s)/%s", envVars.User, envVars.Password, envVars.Host, envVars.Port, envVars.Database)
Olá @R-o-d-r-i-g-o boa tarde!

Realizei a inserção da variável <CONFIG> nas variáveis de ambiente, na struct <environmentVariables> e também na string da config db

2022-07-23 20:10 UTC, RodolfoMRibeiro commented on db/entity/environmentVariables.go
> +func (env *EnvironmentVariables) Load() {
Boa tarde @R-o-d-r-i-g-o tudo bem?

Acabei de realizar a alteração do nome "Load" para "FeedStruct"

2022-07-24 12:35 UTC, R-o-d-r-i-g-o requested changes

2022-07-24 12:35 UTC, R-o-d-r-i-g-o commented on main.go
> +func init() {
já criei em um arquivo routes uma função init, deixa o db.load() lá para que não haja nenhum conflito e também para que seja mais organizado

2022-07-24 12:35 UTC, R-o-d-r-i-g-o commented on db/entity/environmentVariables.go
> +func (env *EnvironmentVariables) FeedStruct() {
dá para entender, mais ainda recomendo que coloque um nome mais objetivo e que a função começe com letra minuscula. Se bem me recordo, a struct apenas será alimentada pela variáveis de ambiente do arquivo .env e este já é chamado na função abaixo por uma biblioteca.

2022-07-24 12:49 UTC, R-o-d-r-i-g-o reviewed
teste

2022-07-24 12:52 UTC, R-o-d-r-i-g-o commented
> dá uma olhada aí se todos os comentários estão em acordo com a realidade

2022-07-24 12:52 UTC, closed without merging

2022-07-24 12:53 UTC, RodolfoMRibeiro commented
> dá uma olhada aí se todos os comentários estão em acordo com a realidade

hhh